# Site settings

# NB! Set your site's url, otherwise nothing will work
url: "https://nsarode.github.io/"
baseurl: ""
# # Google tracking id
# google-tracking-id: "UA-XXXXXXXX-X"

#############
# HTML Head #
#############

lang: "en"
author: "Neha Sarode"
title: "{ Neha Sarode }"
description: "Blog and website of Neha Sarode. Opinions expressed are mine."
keywords: "sarode, neha, personal, jekyll, theme"
favicon: "/img/favicon.ico"
################
# Header layout#
################
black-favicon: "/img/black-lab-glass.ico"
background-img: "intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

quote: "A problem well stated is half solved - Charles Kettering"
# quote: "Since all models are wrong the scientist must be alert to what is importantly wrong - George E.P. Box"
# quote: "As the area of our knowledge grows, so too does our perimeter of ignorance - Neil Degrasse Tyson"
# quote: "Big data is like teenage sex: everyone talks about it, nobody really knows how to do it, everyone thinks everyone else is doing it, so everyone claims they are doing it…"
# me-img: "/img/jetpacktocat.png"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/nsarode.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

#######
# Blog #
########

post-preview-words: 96
paginate: 5
email-share: True
fb-share: False
twitter-share: True
linkedin-share: True
reddit-share: True
tumblr-share: False
pinterest-share: False
pocket-share: True
vkontakte-share: False

disqus-shortname: "personal-jekyll-theme"

############
# Timeline #
############

events:
  - image: "/img/timeline/Ginkgo_Logo.jpg"
    date: "October 2022 - May 2025"
    description: "Decision Science Lead, Data Science & Analytics"
  - image: "/img/timeline/Joynbio_Logo.jpg"
    date: "August 2018 - October 2022"
    description: "Computational Biology Lead, Digital Science & Technology"
  - image: "/img/timeline/Harvard_University_coat_of_arms.png"
    date: "September 2015 - July 2018"
    description: "Post Doctoral Research Associate"
  - image: "/img/timeline/GT.jpg"
    date: "December 2012 - August 2015"
    description: "Post Doctoral Research Faculty"


# First image of the Timeline
timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "neha.sarode@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

author_blurb_image: "/img/author.png"
author_blurb:
  "Data Scientist|Computational Biologist| Microbiologist - Passionate about data and building high-performing teams"

##################
# Social Buttons #
##################

social:
  - icon: "github"
    url: "https://github.com/nsarode"
  - icon: "linkedin-in"
    url: "https://www.linkedin.com/in/nehasarode/"
  - icon: "instagram"
    url: "https://www.instagram.com/nsarode/"
  # - icon: "rss"
  #   url: "https://le4ker.github.io/personal-jekyll-theme/feed.xml"

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Blog: "latest-post"
  Timeline: "timeline"
  Contact: "contact"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
